ln -sf ~/.config/.zshrc ~/.zshrc
ln -sf ~/.config/.gitconfig ~/.gitconfig
ln -sf ~/.config/.condarc ~/.condarc
ln -sf ~/.config/.profile ~/.profile
ln -sf ~/.config/.wget-hsts ~/.wget-hsts
ln -sf ~/.config/.rediscli_history ~/.rediscli_history
ln -sf ~/.config/.mysql_history ~/.mysql_history
ln -sf ~/.config/.lesshst ~/.lesshst
ln -sf ~/.config/.npmrc ~/.npmrc
