-- Import Lua modules
require('core/lazy')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('core/options')
require('lsp/lspconfig')
require('plugins/indent-blankline')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/telescope-file-browser')
require('plugins/conform')
require('plugins/bufferchad')
require('plugins/hardline')
require("barbecue.ui").toggle(true)
